name: Frontend CI/CD Pipeline

env:
  IMAGE_NAME: haphuthinh/markey-fe:latest

on:
  push:
    branches:
      - release

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker image to Docker Hub
        run: docker push $IMAGE_NAME

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy source code to server
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.MARKEY_FRONTEND_SERVER_HOST }}
          username: ${{ secrets.MARKEY_FRONTEND_SERVER_USER }}
          password: ${{ secrets.MARKEY_FRONTEND_SERVER_PASSWORD }}
          source: "./*"
          target: "/root/markey_project/frontend"

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.MARKEY_FRONTEND_SERVER_HOST }}
          username: ${{ secrets.MARKEY_FRONTEND_SERVER_USER }}
          password: ${{ secrets.MARKEY_FRONTEND_SERVER_PASSWORD }}
          port: 22
          script: |
            cd /root/markey_project/frontend/  
            sudo docker compose down  
            sudo docker compose pull     
            sudo docker compose up -d
